config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  get '/login', to: 'home#login'
  get '/search', to: 'home#search'
  get 'profile', to: 'user#index'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:index]
  resources :star, only: [:new, :create]
  resources :user
  resources :projects
  resources :teams

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user.nil?
      redirect_to :action => "login"
    else 
      @top_xp_persons = User.order(xp: :desc).limit(5)
      @top_projects = Project.left_joins(:stars).group(:id).order('COUNT(stars.id) DESC').limit(5)
      @updates = Update.order(created_at: :desc).limit(10)
      @user_results = nil
      @project_results = nil
      @team_results = nil
      render "index"
    end
  end

  def login
    render layout: "login", action: "login"
  end

  def search
    if current_user.nil?
      redirect_to :action => "login"
    else 
      @user_results = User.search(params[:query])
      @project_results = Project.search(params[:query])
      @team_results = Team.search(params[:query])
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def search_helper(query)
    @user_results = User.search(query)
    @project_results = Project.search(query)
    @team_results = Team.search(query)
  end

end

app/views/home/index.html.erb
<div class="feed-container">
  <div class="feed-searchbar-container">
    <%= image_tag image_url("search.svg"), class: "search-icon" %>
    <%= form_tag url_for(:controller => 'home', :action => 'search'), method: "get", class: "feed-searchform" do %>
        <%= text_field_tag(:query, nil, placeholder: "Search Pegasus", class: "feed-searchbar" )%>
    <% end %>
  </div>
  <div class="feed-left">
    <div class="top-exp-persons">
      <p class="feed-header">Top XP</p>
      <p class="feed-right-header">XP</p>
      <% @top_xp_persons.each do |person| %>
        <div class="top-person">
          <%= image_tag image_url(person.image) %>
          <div class="top-person-description">
            <p><%= person.name %></p>
            <p class="top-person-role-team"><%= person.role.nil? || person.role == "" ? "No role set" : person.role %> | <%= person.team.nil? ? "No team set" : person.team.name %></p>
          </div>
          <span><%= person.xp %></span>
        </div>
      <% end %>
    </div>
    <div class="top-projects">
      <p class="feed-header">Top Projects</p>
      <p class="feed-right-header">Stars</p>
      <% @top_projects.each do |p| %>
        <%= link_to project_path(p) do %>
          <div class="top-project">
            <div class="top-project-description">
              <p><%= p.title %></p>
              <p class="top-project-collaborators"><%= truncate(p.description, :length => 60) %></p>
            </div>
            <span><%= p.stars.size %>★</span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div><div class="feed-right">
    <div class="feed-updates">
      <p class="feed-header" style="margin-top: 5px">Updates</p>
        <% @updates.each_with_index do |u, i| %>
        <div class="update <%= i != @updates.length - 1 ? "update-line" : "" %>">
          <%= image_tag image_url(u.user.image) %>
          <div class="update-content">
            <p><%= u.user.name %></p>
            <p class="update-description"><%= u.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/login.html.erb
<div class="login_container">
  <h1>Please Log In</h1>
  <%= link_to image_tag(image_url("btn_google.png"), class: 'btn_google'), "/auth/google_oauth2", id: "sign_in" %>
</div>

app/views/home/search.html.erb
<div class="feed-container">
  <div class="feed-searchbar-container">
    <%= image_tag image_url("search.svg"), class: "search-icon" %>
    <%= form_tag url_for(:controller => 'home', :action => 'search'), method: "get", class: "feed-searchform" do %>
        <%= text_field_tag(:query, params[:query], placeholder: "Search Pegasus", class: "feed-searchbar" )%>
    <% end %>
  </div>
  <div>
    <h4 class="search-header">Search results for ‘<%= params[:query] %>’</h4>
    <%= link_to('< Go Back', home_index_path, class: "btn-go-back") %></p>
  </div>
  <div>
    <div class="feed-left">
      <div class="top-projects">
        <p class="feed-header">Projects</p>
        <% if @project_results.size == 0 %>
          <p class="no-results">No results found</p>
        <% else %>
          <% @project_results.each do |p| %>
            <%= link_to project_path(p.id) do %>
              <div class="top-project">
                <div class="top-project-description">
                  <p><%= p.title %></p>
                  <p class="top-project-collaborators">5 collaborators</p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="top-projects" style="margin-top: 25px">
        <p class="feed-header">Teams</p>
        <% if @team_results.size == 0 %>
          <p class="no-results">No results found</p>
        <% else %>
          <% @team_results.each do |t| %>
            <%= link_to team_path(t.id) do %>
              <div class="top-project">
                <div class="top-project-description">
                  <p><%= t.name %></p>
                  <p class="top-project-collaborators">5 members</p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div><div class="feed-right">
      <div class="feed-updates">
        <p class="feed-header">People</p>
          <% if @user_results.size == 0 %>
            <p class="no-results">No results found</p>
          <% else %>
            <% @user_results.each do |person| %>
              <div class="top-person">
                <%= image_tag image_url(person.image) %>
                <div class="top-person-description">
                  <p><%= person.name %></p>
                  <p class="top-person-role-team"><%= person.role.nil? || person.role == "" ? "No role set" : person.role %></p>
                </div>
                <span><%= person.xp %></span>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>