config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  get '/login', to: 'home#login'
  get '/search', to: 'home#search'
  get 'profile', to: 'user#index'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:index]
  resources :star, only: [:new, :create]
  resources :user
  resources :projects
  resources :teams

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
require 'elasticsearch/model'

class Project < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings do
    mappings dynamic: false do
      indexes :title, type: :text, analyzer: :english
      indexes :description, type: :text, analyzer: :english
    end
  end

  has_many :stars, dependent: :destroy
  has_many :users, :through => :stars

  has_many :project_collaborators, dependent: :destroy
  has_many :users, :through => :project_collaborators
  
  belongs_to :team
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      @my_projects = Project.where(owner: current_user.email)
      render "index"
    end
  end

  def show
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      @project = Project.find(params[:id])
      if @project.nil?
        redirect_to(controller: "projects", action: "index")
        return
      end
      render "show"
    end
  end

  def edit
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      project = Project.find(params[:id])
      if project.nil?
        redirect_to(controller: "projects", action: "index")
        return
      end
      if project.done
        redirect_to(project_path(params[:id]))
        return
      end

      project.done = true
      project.save
      current_user.xp += 5
      current_user.save

      Update.create(
        description: "Edited a project: " + project.title,
        resource_type: "project",
        resource_id: project.id,
        user_id: current_user.id
      )

      redirect_to(project_path(params[:id]))
    end
  end

  def new
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      render "new"
    end      
  end

  def create
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      current_user.xp += 2
      current_user.save

      puts params
      project = Project.create(
        owner: current_user.email,
        title: params[:title],
        stakeholders: params[:stakeholders],
        description: params[:description],
        tasks: params[:tasks],
        milestones: params[:milestones],
        team_id: params[:team][:team],
        office: params[:office],
        priority: params[:priority],
        done: false
      )
      collaborators = params[:collaborators].split(",")
      collaborators.each { |c|
        user = User.find_by(name: c)
        ProjectCollaborator.create(
          user_id: user.id,
          project_id: project.id
        )
      }
      Update.create(
        description: "Created a project: " + project.title,
        resource_type: "project",
        resource_id: project.id,
        user_id: current_user.id
      )
      redirect_to(controller: "projects", action: "index")
    end
  end

  def destroy
    if current_user.nil?
      redirect_to(controller: "home", action: "login")
    else
      project = Project.find(params[:id])
      Update.create(
        description: "Deleted a project: " + project.title,
        resource_type: "project",
        resource_id: project.id,
        user_id: current_user.id
      )
      project.destroy
      redirect_to(controller: "projects", action: "index")
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper

  def get_office_img(office)
    if office == "San Francisco" || office == "San Jose"
      return "america.svg"
    elsif office == "Shanghai"
      return "china.svg"
    elsif office == "Toronto"
      return "canada.svg"
    elsif office == "Amsterdam"
      return "netherlands.svg"
    else
      return ""
    end
  end

  def get_priority_color(priority)
    if priority == "High"
      return "#de350b"
    elsif priority == "Medium"
      return "#ff991f"
    else
      return "#57d9a3"
    end
  end
end

app/views/projects/index.html.erb
<div class="projects-container">
  <h4>My Projects</h4>
  <%= link_to('New Project', new_project_path, class: "btn-new-project") %></p>
  <div class="my-projects">
    <% @my_projects.each do |p| %>
      <%= link_to project_path(p) do %>
        <div class="my-project">
          <div class="my-project-description">
            <p><%= p.title %></p>
            <p class="my-project-collaborators"><%= truncate(p.description, :length => 60) %></p>
          </div>
          <span><%= p.stars.size %> ★</span>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h4>New Project</h4>
<%= link_to '< Go Back', {controller: "projects", action: "index"}, class: "btn-go-back" %>

<%= form_tag(controller: "projects", action: "create") do %>
  <%= label_tag(:title, "Title:") %>
  <%= text_field_tag(:title) %> <br />
  <%= label_tag(:description, "Description:") %>
  <%= text_area_tag(:description) %> <br />
  <%= label_tag(:priority, "Priority") %><br/>
  <%= radio_button_tag "priority", "Low" %>
  <%= label_tag(:priority_low, "Low") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag "priority", "Medium", true %>
  <%= label_tag(:priority_low, "Medium") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= radio_button_tag "priority", "High" %> 
  <%= label_tag(:priority_low, "High") %> <br />
  <%= label_tag(:tasks, "Tasks:") %>
  <%= text_field_tag(:tasks) %> <br />
  <%= label_tag(:milestones, "Milestones:") %>
  <%= text_field_tag(:milestones) %> <br />
  <%= label_tag(:team, "Team:") %>
  <%= collection_select(:team, :team, Team.all, :id, :name, prompt: true) %><br/>
  <%= label_tag(:collaborators, "Collaborators:") %>
  <%= text_field_tag(:collaborators) %> <br />
  <%= label_tag(:stakeholders, "Stakeholders:") %>
  <%= text_field_tag(:stakeholders) %> <br />
  <%= label_tag(:office, "Office:") %>
  <%= select_tag "office", options_for_select([ "San Francisco", "San Jose", "Amsterdam", "Shanghai", "Toronto" ], "San Francisco") %> <br />
  <%= submit_tag "Submit", class: "btn" %>
<% end %>

app/views/projects/show.html.erb
<h4><%= @project.title %></h4>
<%= link_to '< Go back', {controller: "projects", action: "index"}, class: "btn-go-back" %></p>

<div class="project-container">
  <div class="project-left">
    <div class="project-details">
      <p class="projects-header" style="margin-bottom: 13px">Details</p>
      <div class="project-content">
        <h6>Description</h6>
        <p style="font-family: 'Proxima Nova'"><%= @project.description %></p>
      </div>
      <div class="project-content">
        <h6>Priority</h6>
        <p><span class="project-priority" style="background-color: <%= get_priority_color(@project.priority) %>"><%= @project.priority %></span></p>
      </div>
      <div class="project-content">
        <h6>Deadline</h6>
        <p>08/15/2018</p>
      </div>
      <div class="project-content">
        <h6>Office</h6>
        <p><%= image_tag image_url(get_office_img(@project.office)), class: "project-office-img" %><%= @project.office %></p>
      </div>
      <div class="project-content">
        <h6>Team</h6>
        <p><%= @project.team.name %></p>
      </div>
    </div>
    <div class="project-collaborators">
      <p class="projects-header" style="margin-bottom: 15px;">Collaborators (<%= @project.project_collaborators.size %>)</p>
      <% @project.project_collaborators.each do |c| %>
        <div class="project-collaborator">
          <%= image_tag image_url(c.user.image) %>
          <div class="project-collaborator-description">
            <p><%= c.user.name %></p>
            <p class="project-collaborator-role"><%= c.user.role.nil? || c.user.role == "" ? "No role set" : c.user.role %></p>
          </div>
          <%= form_tag(controller: "star", action: "create", project_id: @project.id, receiver_id: c.user.id) do %>
            <%= submit_tag "Give a Star", class: "give-star" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="project-stakeholders">
      <p class="projects-header">Stakeholders (<%= "0" %>)</p>
      <p><%= @project.stakeholders %></p>
    </div>
  </div><div class="project-right">
    <div class="project-milestones">
      <p class="projects-header" style="margin-top: 5px">Milestones</p>
      <p><%= @project.milestones %></p>
    </div>
    <div class="project-tasks">
      <p class="projects-header" style="margin-top: 5px">Tasks</p>
      <p><%= @project.tasks %></p>
    </div>
    <div class="project-stars">
      <p class="projects-header" style="margin-top: 5px;margin-bottom: 15px;">Stars</p>
      <% @project.stars.each do |s| %>
        <div class="project-collaborator">
          <%= image_tag image_url(s.starree.image) %>
          <div class="project-collaborator-description">
            <p><%= s.starree.name %></p>
            <p class="project-collaborator-role">Received from <%= s.starrer.name %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--
<p><%= link_to('Delete project',  @project, method: :delete) %></p>
<p><%= link_to('Complete project', edit_project_path(@project)) %></p>
-->